sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mkulaa1/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkulaa1/docker-react-test npm run test

after_success:
  - docker build -t mkulaa1/multi-client ./client
  - docker build -t mkulaa1/multi-nginx ./nginx
  - docker build -t mkulaa1/multi-server ./server
  - docker build -t mkulaa1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mkulaa1/multi-client
  - docker push mkulaa1/multi-nginx
  - docker push mkulaa1/multi-server
  - docker push mkulaa1/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-673321418693'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY